module tb_mux;

reg a,b,sel;
wire y;
//instantiate the mux
mux uut(

	.a(a),
	.b(b),
	.sel(sel),
	.y(y)
);

initial begin

	$monitor ("time=%ot a=%b b=%b sel=%b y=%b",
	$time ,a,b,sel,y);
        $dumpfile("tb.fsdb");
	$dumpvars(0,tb_mux);

end	

//test cases

initial begin

	a=0; b=0; sel=0; #10;
        a=0; b=1; sel=0; #10;
        a=1; b=0; sel=1; #10;
        a=1; b=1; sel=1; #10;

	$finish;

end

endmodule

